site_name: 此去北疆
site_description: 我的技术笔记
site_url: https://CiQuBeiJiang.github.io
site_dir: site
repo_url: https://github.com/CiQuBeiJiang/CiQuBeiJiang.github.io
theme:
  name: material
  icon:
    logo: material/snowflake  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    # navigation.sections不能加，会冲突


extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css


extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - javascripts/katex.js

nav:
  - 序章: index.md
  - 文学: literary/index.md
  - 哲学: philosophy/index.md
  - 随笔: 
    - 首页: diary/index.md
    - 花: diary/flower.md
  - 机器学习: 
    - 首页: machine_learning/index.md
    - knn算法: machine_learning/KNN.md
    - numpy教程: machine_learning/numpy_tutorial.md
  - 运筹优化: 
    - 首页: optimization/index.md
    - COPT用法: optimization/copt_usage.md
  - 数据分析: 
    - 首页: data_analysis/index.md
    - 数据分析的一般流程: data_analysis/general_process.md

markdown_extensions:
  - admonition
  - pymdownx.highlight 
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:  
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ciqubeijiang
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/XXXXXX
    - icon: fontawesome/solid/paper-plane
      link: mailto:1724961030@qq.com 

copyright: Copyright &copy; 2026 ciqubeijiang. All rights reserved.

plugins:
  - glightbox
  - statistics
  - minify: 
      minify_html: true
      minify_css: true
      minify_js: true
  - git-revision-date-localized:  
      type: date                  
      locale: zh_CN     
  - img2fig  