site_name: 此去北疆
site_description: 我的技术笔记
theme:
  name: material
  icon:
    logo: material/snowflake  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link 
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details        # 折叠面板??? 生效
  - pymdownx.superfences    # 代码块美化
  - pymdownx.tabbed:        # ===选项卡语法 必加！！！
      alternate_style: true
  - pymdownx.emoji:         # fontawesome/material图标 必加！！！
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list               # 让HTML的font标签/行内样式生效
  - md_in_html              # 让markdown里嵌套HTML标签无冲突
nav:
  - 首页: index.md
  - 文学: belles_lettres
  - 哲学: philosophy
  - 随笔: diary
  - 机器学习: machine_learning
  - 运筹优化: optimization
  - 数据分析: data_analysis
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ciqubeijiang
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/XXXXXX
    - icon: fontawesome/solid/paper-plane
      link: mailto:1724961030@qq.com 
copyright: Copyright &copy; 2026 ciqubeijiang. All rights reserved.
extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
statistics:
  enabled: true
plugins:
  - search
  - statistics 